### ISSUE TITLE
A question about  the test dataset

### ISSUE THREAD

**Issue by gushengbo** [IntelLabs/CLNeRF#1]
Hello, could you tell me whether the test datasets are novel views or the train views?    If they are novel views, which the rgb latent should I choose?

**Comment by ZhipengCai** [comment]
Hi,

They are novel views. And the test datasets have corresponding task ID (index of the rgb/geometry latent) assigned, please refer to the dataloader file to check how to decide the task ID for each predefined test view. But if you simply want to render a novel view without computing the testing metrics (PSNR etc), you can take whatever taskID (say we have 5 time steps in total, and you want to see what the scene looks like at time step 2, you just pass the taskID of 2 to the model during rendering) you wish to see and let the model render the image.

**Comment by gushengbo** [comment]
> Hi,
> 
> They are novel views. And the test datasets have corresponding task ID (index of the rgb/geometry latent) assigned, please refer to the dataloader file to check how to decide the task ID for each predefined test view. But if you simply want to render a novel view without computing the testing metrics (PSNR etc), you can take whatever taskID (say we have 5 time steps in total, and you want to see what the scene looks like at time step 2, you just pass the taskID of 2 to the model during rendering) you wish to see and let the model render the image.

Does this mean that a task corresponds to a late code, rather than an image corresponding to a late code?

**Comment by ZhipengCai** [comment]
yes, since we scan all images in the same 'task' together, the scene does not change in its static part
