### ISSUE TITLE
Question about evaluation

### ISSUE THREAD

**Issue by HannahHaensen** [IntelLabs/CLNeRF#2]
![image](https://github.com/IntelLabs/CLNeRF/assets/22636930/64e3eb9a-9c54-4064-969d-6481dbd0fbc1)

Dear authors thanks for providing the code. However, i have some reproduction issues. When cloning the repository and running the validation set, I run into this issue (Image). 

It is nothing OOM. It happens on every scene except for: Kitchen.

I would like to get test images for all scenes (the rep dataset (test_dataloader)) works fine it only happens for validation.

**Comment by ZhipengCai** [comment]
Sorry, I do not fully understand the problem. what do you mean by running validation set? Can you provide the script and dataset that reproduce this result?
