### ISSUE TITLE
Assistance Required for Accessing WAT Dataset for CLNeRF Research

### ISSUE THREAD

**Issue by juhengwei** [IntelLabs/CLNeRF#5]
I encountered an issue with accessing the WAT dataset. Specifically, I used the following command as per the instructions in your paper:

`wget -O ../../dataset/WAT.zip https://huggingface.co/datasets/zcai/WAT-WorldOverTime/resolve/main/WAT.zip`

Unfortunately, this command resulted in an "HTTP 401 Unauthorized" error, indicating that I do not have access permissions for this dataset.
Could you please guide me on how to obtain authorized access to the WAT dataset?

**Comment by Joey2117** [comment]
I had the same issue before. My solution is that you can use the link (https://huggingface.co/datasets/IntelLabs/WAT-WorldAcrossTime) in the github to sign up the account of huggingface and  download WAT dataset.

**Comment by ZhipengCai** [comment]
I think @Joey2117 's solution is the right one. @juhengwei Please do sign in to huggingface and then try to download.
