### ISSUE TITLE
 The confusion regarding the nerf synthetic dataset.

### ISSUE THREAD

**Issue by zl264** [IntelLabs/CLNeRF#9]
Thank you very much for your excellent work. While reading your code, I noticed that you did not add an appearance embedding to NGP when working with the nerf synthetic dataset. Is this because the scene in the nerf synthetic dataset does not change, so the entire scene is captured at a single time step? Is my understanding correct?

**Comment by ZhipengCai** [comment]
yes, for the synthetic data, there is no appearance change theoretically, so no need for the appearance embedding.
